### PR TITLE
flatatt import fix

### LINKED ISSUE #33: ImportError: No module named utils
Tests now failing with:

```
  File "/home/shippable/build_ve/python/2.7/src/django-bootstrap3-datetimepicker/bootstrap3_datetime/widgets.py", line 2, in <module>
    from django.forms.utils import flatatt
ImportError: No module named utils
```

Introduced here: 

https://github.com/nkunihiko/django-bootstrap3-datetimepicker/commit/4e2fa200058820b301b161844e5a012863c80f0b

Fixable with PR https://github.com/nkunihiko/django-bootstrap3-datetimepicker/pull/35, or https://github.com/nkunihiko/django-bootstrap3-datetimepicker/pull/34

### PR DESCRIPTION
**Pull request by roboslone**
Fixes #33 and #59

### CODE REVIEW

**Comment by roboslone** [comment]
@nkunihiko , please merge this =/

**Comment by mbieren** [comment]
Please add this fix. Since Django 1.9 its calles "utils"

**Comment by roboslone** [comment]
@mbieren , are you sure you're in the right thread? My fork does work on both Django 1.9 and 1.10.

**Comment by mbieren** [comment]
Am Dienstag, 18. Oktober 2016, 07:36:26 CEST schrieb roboslone:

> @mbieren , are you sure you're in the right thread? My fork does work on
> both Django 1.9 and 1.10.

@roboslone.

Your pull request is important as it fixes the problems with 1.9 and 1.10. I 
was trying to motivate  nkunihiko to merge your fix. But he was not active the 
last year. Do you have an alternative for his app ?

## 

Michael Bierenfeld 
St.-Martins-Platz 3 
81541 M�nchen 
Tel.: +49 89 69759546 
Mobil: +49 170 4585388 
Fax.: +49 89 69759616

**Comment by roboslone** [comment]
@mbieren , yeah, sorry, I thought you commented in my fork. Thanks for commenting, though I don't think this package is still being maintained.

**Pull request closed without merging**
